---
title: "TEAseq2_QC"
author: "Leroy Bondhus"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
dirs <- list(
)
for(dir in dirs){
  if(!dir.exists(dir)){dir.create(dir)}
};rm(dir)

files <- list(
  
)

```

```{r load packages, echo=FALSE, results='hide'}
req_packages <- list(
  standard = c("BiocManager","doParallel","ggplot2","stringr","data.table","Seurat"),
  biocmanager = c("Gviz","biomaRt")
)
for(std_package in req_packages$standard ){
  if(!require(std_package, quietly=T, character.only=T)){install.packages(std_package)}
};rm(std_package)
for(bioc_package in req_packages$biocmanager ){
  if(!require(bioc_package, quietly=T, character.only=T)){BiocManager::install(bioc_package)}
};rm(bioc_package)
rm(req_packages)
```

```{r}
IB_Tag_Counts <- read.csv("/u/project/arboleda/leroybon/TEMP_SPACE/0460_ADT_HTO_barcounter_out/IB_Tag_Counts.csv")
sc_mat <- Read10X("/u/project/arboleda/leroybon/TEMP_SPACE/0456_0460_arcout/cellranger_count_out_atac_rna/outs/filtered_feature_bc_matrix")
```

```{r}
sc_so_rna <- CreateSeuratObject(counts = sc_mat$`Gene Expression`, min.cells = 3, min.features = 200)
sc_so_atac <- CreateSeuratObject(counts = sc_mat$Peaks, min.cells = 3, min.features = 200)
```


```{r}
sc_so_rna[["percent.mt"]] <- PercentageFeatureSet(sc_so_rna, pattern = "^MT-")
VlnPlot(sc_so_rna, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)


plot1 <- FeatureScatter(sc_so_rna, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(sc_so_rna, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

sc_so_rna <- subset(sc_so_rna, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
sc_so_rna <- NormalizeData(sc_so_rna, normalization.method = "LogNormalize", scale.factor = 10000)


sc_so_rna <- FindVariableFeatures(sc_so_rna, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(sc_so_rna), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(sc_so_rna)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot2


all.genes <- rownames(sc_so_rna)
sc_so_rna <- ScaleData(sc_so_rna, features = all.genes)


sc_so_rna <- RunPCA(sc_so_rna, features = VariableFeatures(object = sc_so_rna))
VizDimLoadings(sc_so_rna, dims = 1:4, reduction = "pca")


DimPlot(sc_so_rna, reduction = "pca")

DimHeatmap(sc_so_rna, dims = 1:15, cells = 500, balanced = TRUE)


ElbowPlot(sc_so_rna)

sc_so_rna <- FindNeighbors(sc_so_rna, dims = 1:10)
sc_so_rna <- FindClusters(sc_so_rna, resolution = 0.5)


sc_so_rna <- RunUMAP(sc_so_rna, dims = 1:10)
DimPlot(sc_so_rna, reduction = "umap")

FeaturePlot(sc_so_rna, features = c("MS4A1", "GNLY", "CD3E", "CD14", "FCER1A", "FCGR3A", "LYZ", "PPBP",
    "CD8A"))
```